export const NEW_SELECTED_COUNTRY = 'NEW_SELECTED_COUNTRY'

export const COUNTRY_REQUEST = 'COUNTRY_REQUEST'
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS'
export const GET_COUNTRY_FAILED = 'GET_COUNTRY_FAILED'


